import React from 'react';
    export const Items = [
        {
            id: 1,
            brand: "Toyota",
            model: "Corolla",
            year: 2018,
            condition: "Used",
            img: "..",
            title: "17×7 Toyota Corolla Rim 2018 (42611Y540)",
            price: 300,
            chips: ["Wheels"],
            },
            {
            id: 2,
            brand: "Toyota",
            model: "Vitz",
            year: 2014,
            condition: "Used",
            img: "/images/wheels/toyota_vitz_bumper.jpg",
            title: "Front Bumper – Toyota Vitz 2014 (RS)",
            price: 300,
            chips: ["Body"],
            },
            {
            id: 3,
            brand: "Chevrolet",
            model: "Camaro",
            year: 2016,
            condition: "New",
            img: "/images/wheels/camaro_steering_wheel.jpg",
            title: "Camaro Carbon Steering Wheel (C16+)",
            price: 799.99,
            chips: ["Interior"],
            },
            {
                id: 4,
                brand: "Toyota",
                model: "Vitz",
                year: 2014,
                condition: "Used",
                img: "/images/wheels/toyota_vitz_bumper.jpg",
                title: "Front Bumper – Toyota Vitz 2014 (RS)",
                price: 300,
                chips: ["Body"],
                },
                {
                    id: 5,
                    brand: "Toyota",
                    model: "Vitz",
                    year: 2014,
                    condition: "Used",
                    img: "/images/wheels/toyota_vitz_bumper.jpg",
                    title: "Front Bumper – Toyota Vitz 2014 (RS)",
                    price: 300,
                    chips: ["Body"],
                    },
                    {
                    id: 6,
                    brand: "Toyota",
                    model: "Vitz",
                    year: 2014,
                    condition: "Used",
                    img: "/images/wheels/toyota_vitz_bumper.jpg",
                    title: "Front Bumper – Toyota Vitz 2014 (RS)",
                    price: 300,
                    chips: ["Body"],
                    },
                    {
                    id: 7,
                    brand: "Toyota",
                    model: "Vitz",
                    year: 2014,
                    condition: "Used",
                    img: "/images/wheels/toyota_vitz_bumper.jpg",
                    title: "Front Bumper – Toyota Vitz 2014 (RS)",
                    price: 300,
                    chips: ["Body"],
                    },
                    {
                    id: 8,
                    brand: "Toyota",
                    model: "Vitz",
                    year: 2014,
                    condition: "Used",
                    img: "/images/wheels/toyota_vitz_bumper.jpg",
                    title: "Front Bumper – Toyota Vitz 2014 (RS)",
                    price: 300,
                    chips: ["Body"],
                    },
                    {
                    id: 9,
                    brand: "Toyota",
                    model: "Vitz",
                    year: 2014,
                    condition: "Used",
                    img: "/images/wheels/toyota_vitz_bumper.jpg",
                    title: "Front Bumper – Toyota Vitz 2014 (RS)",
                    price: 300,
                    chips: ["Body"],
                    },
                    {
                    id: 10,
                    brand: "Toyota",
                    model: "Vitz",
                    year: 2014,
                    condition: "Used",
                    img: "/images/wheels/toyota_vitz_bumper.jpg",
                    title: "Front Bumper – Toyota Vitz 2014 (RS)",
                    price: 300,
                    chips: ["Body"],
                    },
                    {
                    id: 11,
                    brand: "Toyota",
                    model: "Vitz",
                    year: 2014,
                    condition: "Used",
                    img: "/images/wheels/toyota_vitz_bumper.jpg",
                    title: "Front Bumper – Toyota Vitz 2014 (RS)",
                    price: 300,
                    chips: ["Body"],
                    },
                    {
                    id: 12,
                    brand: "Toyota",
                    model: "Vitz",
                    year: 2014,
                    condition: "Used",
                    img: "/images/wheels/toyota_vitz_bumper.jpg",
                    title: "Front Bumper – Toyota Vitz 2014 (RS)",
                    price: 300,
                    chips: ["Body"],
                    }
    ];        